// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.milibris.foundation.Foundation`
class Foundation extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<Foundation> $type;

  @jni$_.internal
  Foundation.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/milibris/foundation/Foundation',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Foundation?> nullableType =
      $Foundation$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Foundation> type = $Foundation$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Foundation() {
    return Foundation.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_errorMessage = _class.staticMethodId(
    r'errorMessage',
    r'(Landroid/content/Context;)V',
  );

  static final _errorMessage =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public void errorMessage(android.content.Context context)`
  static void errorMessage(jni$_.JObject? context) {
    final _$context = context?.reference ?? jni$_.jNullReference;
    _errorMessage(
      _class.reference.pointer,
      _id_errorMessage as jni$_.JMethodIDPtr,
      _$context.pointer,
    ).check();
  }

  static final _id_toApp = _class.staticMethodId(
    r'toApp',
    r'(Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _toApp =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public java.lang.String toApp(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? toApp(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _toApp(
      _class.reference.pointer,
      _id_toApp as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_toUsr = _class.staticMethodId(
    r'toUsr',
    r'(Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _toUsr =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public java.lang.String toUsr(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? toUsr(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _toUsr(
      _class.reference.pointer,
      _id_toUsr as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_createContext = _class.staticMethodId(
    r'createContext',
    r'(Landroid/content/Context;)Lcom/milibris/foundation/FoundationContext;',
  );

  static final _createContext =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public com.milibris.foundation.FoundationContext createContext(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  static FoundationContext? createContext(jni$_.JObject? context) {
    final _$context = context?.reference ?? jni$_.jNullReference;
    return _createContext(
      _class.reference.pointer,
      _id_createContext as jni$_.JMethodIDPtr,
      _$context.pointer,
    ).object<FoundationContext?>(const $FoundationContext$NullableType$());
  }

  static final _id_createContext$1 = _class.staticMethodId(
    r'createContext',
    r'(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;)Lcom/milibris/foundation/FoundationContext;',
  );

  static final _createContext$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public com.milibris.foundation.FoundationContext createContext(android.content.Context context, java.lang.String string, java.lang.String string1)`
  /// The returned object must be released after use, by calling the [release] method.
  static FoundationContext? createContext$1(
    jni$_.JObject? context,
    jni$_.JString? string,
    jni$_.JString? string1,
  ) {
    final _$context = context?.reference ?? jni$_.jNullReference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    return _createContext$1(
      _class.reference.pointer,
      _id_createContext$1 as jni$_.JMethodIDPtr,
      _$context.pointer,
      _$string.pointer,
      _$string1.pointer,
    ).object<FoundationContext?>(const $FoundationContext$NullableType$());
  }
}

final class $Foundation$NullableType$ extends jni$_.JType<Foundation?> {
  @jni$_.internal
  const $Foundation$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/milibris/foundation/Foundation;';

  @jni$_.internal
  @core$_.override
  Foundation? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : Foundation.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Foundation?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Foundation$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Foundation$NullableType$) &&
        other is $Foundation$NullableType$;
  }
}

final class $Foundation$Type$ extends jni$_.JType<Foundation> {
  @jni$_.internal
  const $Foundation$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/milibris/foundation/Foundation;';

  @jni$_.internal
  @core$_.override
  Foundation fromReference(jni$_.JReference reference) =>
      Foundation.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Foundation?> get nullableType =>
      const $Foundation$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Foundation$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Foundation$Type$) &&
        other is $Foundation$Type$;
  }
}

/// from: `com.milibris.foundation.FoundationContext`
class FoundationContext extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<FoundationContext> $type;

  @jni$_.internal
  FoundationContext.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/milibris/foundation/FoundationContext',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<FoundationContext?> nullableType =
      $FoundationContext$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<FoundationContext> type = $FoundationContext$Type$();
  static final _id_getToken = _class.instanceMethodId(
    r'getToken',
    r'()Ljava/lang/String;',
  );

  static final _getToken =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getToken()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getToken() {
    return _getToken(
      reference.pointer,
      _id_getToken as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getContext = _class.instanceMethodId(
    r'getContext',
    r'()Landroid/content/Context;',
  );

  static final _getContext =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.content.Context getContext()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getContext() {
    return _getContext(
      reference.pointer,
      _id_getContext as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject?>(const jni$_.$JObject$NullableType$());
  }

  static final _id_getApp = _class.instanceMethodId(r'getApp', r'()[B');

  static final _getApp =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public byte[] getApp()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JByteArray? getApp() {
    return _getApp(
      reference.pointer,
      _id_getApp as jni$_.JMethodIDPtr,
    ).object<jni$_.JByteArray?>(const jni$_.$JByteArray$NullableType$());
  }

  static final _id_getUsr = _class.instanceMethodId(r'getUsr', r'()[B');

  static final _getUsr =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public byte[] getUsr()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JByteArray? getUsr() {
    return _getUsr(
      reference.pointer,
      _id_getUsr as jni$_.JMethodIDPtr,
    ).object<jni$_.JByteArray?>(const jni$_.$JByteArray$NullableType$());
  }
}

final class $FoundationContext$NullableType$
    extends jni$_.JType<FoundationContext?> {
  @jni$_.internal
  const $FoundationContext$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/milibris/foundation/FoundationContext;';

  @jni$_.internal
  @core$_.override
  FoundationContext? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : FoundationContext.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<FoundationContext?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($FoundationContext$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($FoundationContext$NullableType$) &&
        other is $FoundationContext$NullableType$;
  }
}

final class $FoundationContext$Type$ extends jni$_.JType<FoundationContext> {
  @jni$_.internal
  const $FoundationContext$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/milibris/foundation/FoundationContext;';

  @jni$_.internal
  @core$_.override
  FoundationContext fromReference(jni$_.JReference reference) =>
      FoundationContext.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<FoundationContext?> get nullableType =>
      const $FoundationContext$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($FoundationContext$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($FoundationContext$Type$) &&
        other is $FoundationContext$Type$;
  }
}

/// from: `com.milibris.foundation.CompleteArchive`
class CompleteArchive extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<CompleteArchive> $type;

  @jni$_.internal
  CompleteArchive.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/milibris/foundation/CompleteArchive',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<CompleteArchive?> nullableType =
      $CompleteArchive$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<CompleteArchive> type = $CompleteArchive$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Lcom/milibris/foundation/FoundationContext;Ljava/io/FileInputStream;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(com.milibris.foundation.FoundationContext foundationContext, java.io.FileInputStream fileInputStream)`
  /// The returned object must be released after use, by calling the [release] method.
  factory CompleteArchive(
    FoundationContext foundationContext,
    jni$_.JObject? fileInputStream,
  ) {
    final _$foundationContext = foundationContext.reference;
    final _$fileInputStream =
        fileInputStream?.reference ?? jni$_.jNullReference;
    return CompleteArchive.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$foundationContext.pointer,
        _$fileInputStream.pointer,
      ).reference,
    );
  }

  static final _id_new$1 = _class.constructorId(
    r'(Lcom/milibris/foundation/FoundationContext;Landroid/net/Uri;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(com.milibris.foundation.FoundationContext foundationContext, android.net.Uri uri)`
  /// The returned object must be released after use, by calling the [release] method.
  factory CompleteArchive.new$1(
    FoundationContext? foundationContext,
    jni$_.JObject? uri,
  ) {
    final _$foundationContext =
        foundationContext?.reference ?? jni$_.jNullReference;
    final _$uri = uri?.reference ?? jni$_.jNullReference;
    return CompleteArchive.fromReference(
      _new$1(
        _class.reference.pointer,
        _id_new$1 as jni$_.JMethodIDPtr,
        _$foundationContext.pointer,
        _$uri.pointer,
      ).reference,
    );
  }

  static final _id_new$2 = _class.constructorId(
    r'(Lcom/milibris/foundation/FoundationContext;Ljava/io/File;)V',
  );

  static final _new$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(com.milibris.foundation.FoundationContext foundationContext, java.io.File file)`
  /// The returned object must be released after use, by calling the [release] method.
  factory CompleteArchive.new$2(
    FoundationContext? foundationContext,
    jni$_.JObject? file,
  ) {
    final _$foundationContext =
        foundationContext?.reference ?? jni$_.jNullReference;
    final _$file = file?.reference ?? jni$_.jNullReference;
    return CompleteArchive.fromReference(
      _new$2(
        _class.reference.pointer,
        _id_new$2 as jni$_.JMethodIDPtr,
        _$foundationContext.pointer,
        _$file.pointer,
      ).reference,
    );
  }

  static final _id_new$3 = _class.constructorId(
    r'(Lcom/milibris/foundation/FoundationContext;Ljava/lang/String;)V',
  );

  static final _new$3 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(com.milibris.foundation.FoundationContext foundationContext, java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  factory CompleteArchive.new$3(
    FoundationContext? foundationContext,
    jni$_.JString? string,
  ) {
    final _$foundationContext =
        foundationContext?.reference ?? jni$_.jNullReference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    return CompleteArchive.fromReference(
      _new$3(
        _class.reference.pointer,
        _id_new$3 as jni$_.JMethodIDPtr,
        _$foundationContext.pointer,
        _$string.pointer,
      ).reference,
    );
  }

  static final _id_unpackTo = _class.instanceMethodId(
    r'unpackTo',
    r'(Ljava/io/File;)Lcom/milibris/foundation/Release;',
  );

  static final _unpackTo =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public com.milibris.foundation.Release unpackTo(java.io.File file)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? unpackTo(jni$_.JObject? file) {
    final _$file = file?.reference ?? jni$_.jNullReference;
    return _unpackTo(
      reference.pointer,
      _id_unpackTo as jni$_.JMethodIDPtr,
      _$file.pointer,
    ).object<jni$_.JObject?>(const jni$_.$JObject$NullableType$());
  }

  static final _id_unpackTo$1 = _class.instanceMethodId(
    r'unpackTo',
    r'(Ljava/lang/String;)Lcom/milibris/foundation/Release;',
  );

  static final _unpackTo$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public com.milibris.foundation.Release unpackTo(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? unpackTo$1(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _unpackTo$1(
      reference.pointer,
      _id_unpackTo$1 as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).object<jni$_.JObject?>(const jni$_.$JObject$NullableType$());
  }

  static final _id_unpackTo$2 = _class.instanceMethodId(
    r'unpackTo',
    r'(Landroid/net/Uri;)Lcom/milibris/foundation/Release;',
  );

  static final _unpackTo$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public com.milibris.foundation.Release unpackTo(android.net.Uri uri)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? unpackTo$2(jni$_.JObject uri) {
    final _$uri = uri.reference;
    return _unpackTo$2(
      reference.pointer,
      _id_unpackTo$2 as jni$_.JMethodIDPtr,
      _$uri.pointer,
    ).object<jni$_.JObject?>(const jni$_.$JObject$NullableType$());
  }
}

final class $CompleteArchive$NullableType$
    extends jni$_.JType<CompleteArchive?> {
  @jni$_.internal
  const $CompleteArchive$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/milibris/foundation/CompleteArchive;';

  @jni$_.internal
  @core$_.override
  CompleteArchive? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : CompleteArchive.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<CompleteArchive?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($CompleteArchive$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($CompleteArchive$NullableType$) &&
        other is $CompleteArchive$NullableType$;
  }
}

final class $CompleteArchive$Type$ extends jni$_.JType<CompleteArchive> {
  @jni$_.internal
  const $CompleteArchive$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/milibris/foundation/CompleteArchive;';

  @jni$_.internal
  @core$_.override
  CompleteArchive fromReference(jni$_.JReference reference) =>
      CompleteArchive.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<CompleteArchive?> get nullableType =>
      const $CompleteArchive$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($CompleteArchive$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($CompleteArchive$Type$) &&
        other is $CompleteArchive$Type$;
  }
}
