// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `src/milibris_reader.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class MilibrisReaderBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MilibrisReaderBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MilibrisReaderBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Extracts a Milibris .complete archive to the destination directory.
  /// archive_path: absolute path to the .complete archive file.
  /// dest_path:    absolute path to the directory where the archive is extracted.
  /// Returns 0 on success, negative error code on failure.
  int milibris_extract_archive(
    ffi.Pointer<ffi.Char> archive_path,
    ffi.Pointer<ffi.Char> dest_path,
  ) {
    return _milibris_extract_archive(archive_path, dest_path);
  }

  late final _milibris_extract_archivePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('milibris_extract_archive');
  late final _milibris_extract_archive = _milibris_extract_archivePtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();
}
