// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

late final _class_MLArchive = objc.getClass("MLArchive");
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
final _objc_msgSend_19nvye5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
typedef instancetype = ffi.Pointer<objc.ObjCObjectImpl>;
typedef Dartinstancetype = objc.ObjCObject;
late final _sel_init = objc.registerName("init");
final _objc_msgSend_151sglz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_extract_inDirectory_error_ = objc.registerName(
  "extract:inDirectory:error:",
);
final _objc_msgSend_6z4k82 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>>,
      )
    >();
late final _sel_createZipAt_sourceFiles_error_ = objc.registerName(
  "createZipAt:sourceFiles:error:",
);
late final _sel_createTarGzAt_sourceFiles_error_ = objc.registerName(
  "createTarGzAt:sourceFiles:error:",
);
late final _sel_new = objc.registerName("new");
late final _sel_allocWithZone_ = objc.registerName("allocWithZone:");
final _objc_msgSend_1cwp428 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.NSZone>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.NSZone>,
      )
    >();
late final _sel_alloc = objc.registerName("alloc");

/// MLArchive
extension type MLArchive._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [MLArchive] that points to the same underlying object as [other].
  MLArchive.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [MLArchive] that wraps the given raw object pointer.
  MLArchive.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [MLArchive].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_MLArchive,
  );

  /// alloc
  static MLArchive alloc() {
    final $ret = _objc_msgSend_151sglz(_class_MLArchive, _sel_alloc);
    return MLArchive.fromPointer($ret, retain: false, release: true);
  }

  /// allocWithZone:
  static MLArchive allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_MLArchive,
      _sel_allocWithZone_,
      zone,
    );
    return MLArchive.fromPointer($ret, retain: false, release: true);
  }

  /// createTarGzAt:sourceFiles:error:
  static bool createTarGzAt(
    objc.NSURL archiveURL, {
    required objc.NSArray sourceFiles,
    required ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>> error,
  }) {
    return _objc_msgSend_6z4k82(
      _class_MLArchive,
      _sel_createTarGzAt_sourceFiles_error_,
      archiveURL.ref.pointer,
      sourceFiles.ref.pointer,
      error,
    );
  }

  /// createZipAt:sourceFiles:error:
  static bool createZipAt(
    objc.NSURL archiveURL, {
    required objc.NSArray sourceFiles,
    required ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>> error,
  }) {
    return _objc_msgSend_6z4k82(
      _class_MLArchive,
      _sel_createZipAt_sourceFiles_error_,
      archiveURL.ref.pointer,
      sourceFiles.ref.pointer,
      error,
    );
  }

  /// extract:inDirectory:error:
  static bool extract(
    objc.NSURL archiveURL, {
    required objc.NSURL inDirectory,
    required ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>> error,
  }) {
    return _objc_msgSend_6z4k82(
      _class_MLArchive,
      _sel_extract_inDirectory_error_,
      archiveURL.ref.pointer,
      inDirectory.ref.pointer,
      error,
    );
  }

  /// new
  static MLArchive new$() {
    final $ret = _objc_msgSend_151sglz(_class_MLArchive, _sel_new);
    return MLArchive.fromPointer($ret, retain: false, release: true);
  }

  /// Returns a new instance of MLArchive constructed with the default `new` method.
  MLArchive() : this.as(new$().object$);
}

extension MLArchive$Methods on MLArchive {
  /// init
  MLArchive init() {
    objc.checkOsVersionInternal(
      'MLArchive.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return MLArchive.fromPointer($ret, retain: false, release: true);
  }
}
